config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :users
  get '/profile' => 'users#profile'
  resources :properties
  resources :applications
  post 'applications/:id' => 'applications#edit'
  resources :feedbacks

end

app/models/application.rb
class Application < ApplicationRecord

  # Feedback
  belongs_to :applicant_feedback, class_name: 'Feedback', optional: true
  belongs_to :owner_feedback, class_name: 'Feedback', optional: true
  belongs_to :applicant, class_name: 'User', foreign_key: 'user_id'
  belongs_to :property, optional: true
  enum status: [:pending, :approved, :rejected]
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  enum ease: [:poor, :average, :normal, :good, :great], _prefix: true
  enum communication: [:slowest, :slow, :normal, :fast, :fastest], _prefix: true
  enum interaction: [:awful, :icy, :normal, :easy, :friendly], _prefix: true
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  has_many :applications

  #Geocoding
  after_validation :geocode
  geocoded_by :address

end

app/models/user.rb
class User < ApplicationRecord

  has_many :applications, foreign_key: 'user_id'
  has_many :properties # i.e. properties owned by this user
  has_many :owner_applications, through: :properties, source: :applications
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # This will cause fetch user to run before anything
  before_action :fetch_user

  def fetch_user

    # check if the user_id in the session hash is the ID of a real user
    # in our users table: if it is, get object for that user and save it into
    # @current_user which every controller can use; if it's not a real ID,
    # consider it invalid and delete the session. This will prevent weird
    # errors when re-seeding our DB
    if session[:user_id].present?
      @current_user = User.find_by id: session[:user_id]
    end
    session[:user_id] = nil unless @current_user.present?
  end #fetch_user

  # Check if user is logged in before accessing relevant pages
  def check_if_logged_in
    # if the current request is coming from a user who is not logged in
    # redirect them to the login page
    # any controller actions that should only be available to
    # logged in users will need to run this method before performing
    unless @current_user.present?
      flash[:error] = 'You must be logged in to perform that action'
      redirect_to login_path
    end # unless
  end # check_if_logged_in
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :check_if_logged_in

  def new
    @application = Application.new
    @address = params[:param1]
  end

  def create
    application = Application.create property_id: params[:property_id], user_id: @current_user.id
    redirect_to application_path(application.id)
  end

  def index
    @applications = Application.all
    @properties = Property.all

  end

  def show
    @application = Application.find params[:id]
    # raise 'hell'
  end

  def edit
    @application = Application.find params[:id]
  end

  def update
    application = Application.find params[:id]

    application.update status: params[:application][:status]
    application.save
    redirect_to application_path(application.id)
  end

  def destroy
  end

  private

  def application_params
    params.require(:application).permit(:property_id)
  end

end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def new
    @feedback = Feedback.new
  end

  def create
    # raise 'hell'
    feedback = Feedback.create(
      application_id: params[:feedback][:application_id],
      ease: params[:feedback][:ease], communication: params[:feedback][:communication], interaction: params[:feedback][:interaction]
    )
    # now that we have saved the feedback we have to save its ID to the appropriate field in the corresponding application: applicant_feedback_id or owner_feedback_id
    application = Application.find params[:feedback][:application_id]
    if @current_user.user_type == 'owner'
      application.update applicant_feedback_id: feedback.id
    else
      # if not the owner, it must be the applicant
      application.update owner_feedback_id: feedback.id
    end # user_type conditional
    redirect_to application_path(application.id)
  end # create

  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def new
  end

  def create
  end

  def index
    @properties = Property.all
  end

  def show
    @property = Property.find params[:id]
    @status = ['Just Posted', 'Holding Inspections', 'Seeking Applications', 'Pending Application', 'Leased'] # status options
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/propertys_controller.rb
class PropertysController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    # raise 'hell'
    #1. check if the email address entered is actually in the users table
    user = User.find_by email: params[:email]
    #2. did we actually find a user for that email address or was it nil?
    # and if we did find the user, is the password correct?
    if user.present? && user.authenticate(params[:password])
      #credentials were correct - login successful
      session[:user_id] = user.id

      redirect_to root_path
    else
      #either the user was nil (no email match) or no password match
      flash[:error] = 'Invalid email or password'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil # this logs out the user
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_logged_in, only: [:profile, :edit, :update]

  def new
    @user = User.new
  end # new

  def create
    @user = User.create
    if @user.persisted?
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end # if persisted
  end # create

  def index
  end

  def show
    @user = User.find params[:id]
  end

  def profile
    @properties = Property.all
    @applications = Application.all
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end # user_params

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/propertys_helper.rb
module PropertysHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/applications/edit.html.erb
<h3>Update Application</h3>

<h2 class="application">Application for:<%=@application.property.address%></h2>

<p>
  <strong>Applicant Name:</strong>
  <%= @application.applicant.name %>
</p>
<p class="feedback">
  <strong>Applicant Feedback:</strong>
  <%= @application.applicant_feedback.ease %>
</p>
<p>
  <strong>Owner Name:</strong>
  <%= @application.property.owner.name %>
</p>
<p class="feedback">
  <strong>Owner Feedback:</strong>
  <%= @application.owner_feedback.ease %>
</p>
<p>
  <strong>Application Decision:</strong>
  <%= @application.status %>
</p>

<%if @current_user.user_type == 'owner'%>
  <%= form_with model: @application, local: true do |f| %>
    <%= f.label :status %>
    <br>
    <%= f.select :status, Application.statuses.keys, :prompt => 'Select One' %>
    <br>
    <%= f.submit 'Update Application' %>
  <% end %>
<% end %>

app/views/applications/index.html.erb
<h3>Your Applications</h3>

<% if @current_user.user_type == 'owner' %>
  <% @current_user.owner_applications.each do |owner_app| %>
    <li>
      <%= link_to owner_app.property.address, application_path(owner_app.id) %>
    </li>
  <% end %>
<% end %>
<% @current_user.applications.each do |app| %>
    <li>
      <%= link_to app.property.address, application_path(app.id) %>
    </li>
<% end %>
</ul>

app/views/applications/new.html.erb
<h3>Create a New Application</h3>
<!-- Needs to contain the following: -->
<!-- Property Address which could be given as params after clicking apply-->
<!-- other data relating to the property, such as the ID could be used to get the owner-->
<!-- there could also be params data from the current user -->
<!-- form_with -->

<%= form_with model: @application, local: true do |f| %>
    <%= f.label :name %>
    <br>
    <%= f.text_field :name, value: @current_user.name %>
  <br>
    <%= f.label :address %>
    <br>
    <%= f.text_field :address, value: @address %>

<%= f.submit 'Send Application' %>
<% end %>

app/views/applications/show.html.erb
<h2 class="application">Application for: <%=@application.property.address%></h2>

<p>
  <strong>Applicant Name:</strong>
  <%= @application.applicant.name %>
</p>
<p class="feedback">
  <strong>Applicant Feedback:</strong>
  <%= @application.applicant_feedback.ease %>
</p>
<p>
  <strong>Owner Name:</strong>
  <%= @application.property.owner.name %>
</p>
<p class="feedback">
  <strong>Owner Feedback:</strong>
  <%= @application.owner_feedback.ease %>
</p>
<p>
  <strong>Application Decision:</strong>
  <%= @application.status %>
</p>

<%if @current_user.user_type == 'owner'%>
  <%= form_with model: @application, local: true do |f| %>
    <%= f.label :status %>
    <br>
    <%= f.select :status, Application.statuses.keys, :prompt => 'Select One' %>
    <br>
    <%= f.submit 'Update Application' %>
  <% end %>
<% end %>

<% unless @application.pending? %>
<h2 class="market">Please Give Feedback</h2>
<%= form_with model: Feedback.new, local: true do |f| %>
  <%= f.label :ease, 'How was the overall experience?' %>
  <br>
  <%= f.select :ease, Feedback.eases.keys, :prompt => 'Select One' %>
  <br>
  <%= f.label :communication, 'How quickly did you hear back from the other party?' %>
  <br>
  <%= f.select :communication, Feedback.communications.keys, :prompt => 'Select One' %>
  <br>
  <%= f.label :interaction, 'How were they to deal with?' %>
  <br>
  <%= f.select :interaction, Feedback.interactions.keys, :prompt => 'Select One' %>
  <br>
  <br>
  <%= f.hidden_field :application_id, value: @application.id %>
  <%= f.submit 'Send Feedback' %>
  <% end %>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Feedbacks#edit</h1>
<p>Find me in app/views/feedbacks/edit.html.erb</p>

app/views/feedbacks/index.html.erb
<h1>Feedbacks#index</h1>
<p>Find me in app/views/feedbacks/index.html.erb</p>

app/views/feedbacks/new.html.erb
<h2>How was your experience?</h2>

<%= form_with model: @feedback, local: true do |f| %>
  <%= f.label :interaction %>
  <br>
  <%= f.text_field :interaction %>
  <br>
  <%= f.label :ease %>
  <br>
  <%= f.text_field :ease %>
  <br>
  <br>
  <%= f.label :interaction %>
  <br>
  <%= f.text_field :interaction %>
  <br>
  <br>
  <%= f.submit 'Share Feedback' %>

  <% end %>

app/views/feedbacks/show.html.erb
<h1>Feedbacks#show</h1>
<p>Find me in app/views/feedbacks/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reality</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <header>
    <h1 id="title">Reality</h1>
  </header>
  <body>
    <h2 class="market">
    <% if @current_user.present? %>
    Welcome, <%= @current_user.name %>
    <% end %>
    </h2>
    <nav>
      <%= link_to 'Home', root_path %>
      <% if @current_user.present? %>
        <%= link_to 'Logout', login_path, method: 'delete' %>
        <%= link_to 'My Profile', profile_path %>
        <%= link_to 'My Applications', applications_path %>
      <% else %>
        <%= link_to 'Login', login_path %>
        <%= link_to 'Sign Up', new_user_path %>
      <% end %>
      <%= link_to 'Marketplace', properties_path %>
    <hr>
    </nav>
    <%= yield %>
  </body>
  <footer>
    <hr>
    &copy; Alistair Gray 2020
  </footer>
</html>

app/views/pages/home.html.erb
<h1 class="hero">Putting the humanity back in real estate</h1>

<%= image_tag '/assets/hero.jpg' %>

app/views/properties/edit.html.erb
<h1>Propertys#edit</h1>
<p>Find me in app/views/propertys/edit.html.erb</p>

app/views/properties/index.html.erb
<h2 class="market">Marketplace</h2>
<hr>
<ul>
  <% @properties.each do |p| %>
  <li>
    <%= link_to p.address, property_path(p.id) %>
    <br>
    <br>
    <%= image_tag p.image %>
    <hr>
  </li>
  <% end %>
</ul>

app/views/properties/new.html.erb
<h1>Propertys#new</h1>
<p>Find me in app/views/propertys/new.html.erb</p>

<!-- # add cloudinary -->
<%= f.label :image %>
<%= f.file_field :image %>

app/views/properties/show.html.erb
<h3>Details for: <%= @property.address%></h3>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBpKKvUvI8IOkHtDoaIHY45KaIbUPs0Uaw&callback=initMap&libraries=&v=weekly"defer></script>
<style>
  #map {
    width: 50vw;
    height: 50vw;
  }
</style>
<script>

const property = {lat: <%= @property.latitude %>, lng: <%= @property.longitude %>};

function initMap(){
  const map = new google.maps.Map(
    document.getElementById("map"),
    {
      zoom: 16,
      center: property,
    }
  );

  new google.maps.Marker({
    position: property,
    map,
    title: "Property Location",
  });
}
</script>

<p>
  <strong>Number of bedrooms:</strong>
  <%= @property.bedrooms %>
</p>
<p>
  <strong>Status:</strong>
  <%= @status[@property.status] %>
</p>
<br>
<hr>
<%=image_tag @property.image %>
<hr>
<p>Property Location</p>
<div id="map">


</div>

<% if @current_user.id == @property.user_id %>
<% else %>
<%= link_to 'Apply', applications_path(property_id: @property.id), method: 'post' %>
<% end %>

app/views/session/new.html.erb
<h3>Login</h3>

<% if flash[:error] %>
<br>
<strong>
  <%= flash[:error] %>
</strong>
<br>
<br>
<% end %>

<%= form_with url: login_path, local: true do |f| %>

  <%= f.label :email %><br>
  <%= f.text_field :email %><br>
  <br>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br>
  <br>

  <%= f.submit 'Login' %>

<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h3>Create an Account</h3>

<% if @user.errors.full_messages.any? %>
<strong>Please correct the following errors:</strong>
<ul>
  <% @user.errors.full_messages.each do |error| %>
  <li><%=error%></li>
  <% end %>
</ul>
<% end %>

<%= form_with model: @user, local: true do |f| %>
  <%= f.label :user_type, 'owner or applicant?'%>
  <br>
  <%= f.text_field :user_type %>
  <br>
  <%= f.label :name %>
  <br>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <br>
  <%= f.text_field :email %>
  <br>
  <%= f.label :password %>
  <br>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <br>
  <%= f.password_field :password_confirmation %>
  <br>
  <br>
  <%= f.submit 'Sign Up' %>

<% end %>

app/views/users/profile.html.erb
<h3>Hi <%=@current_user.name%>, here is your profile</h3>

<p>
  <strong>Email:</strong>
  <%= @current_user.email%>
</p>
<br>
<p>
  <strong>Reality User Type:</strong>
  <%= @current_user.user_type%>
</p>
<br>
<p><strong>Pending Applications:</strong></p>
<ul>
<% if @current_user.user_type == 'owner' %>
  <% @current_user.owner_applications.each do |owner_app| %>
    <li>
      <%= link_to owner_app.property.address, application_path(owner_app.id) %>
    </li>
  <% end %>
<% end %>
</ul>
<ul>
<% @current_user.applications.each do |app| %>
    <li>
      <%= link_to app.property.address, application_path(app.id) %>
    </li>
<% end %>
</ul>

  <strong>My Properties:</strong>
  <% if @current_user.user_type == 'owner'%>
    <ul>
    <% @current_user.properties.each do |p| %>
      <li>
          <%= link_to p.address, property_path(p.id)%>
      </li>

    <% end %>
    </ul>
  <% end %>

app/views/users/show.html.erb
<h3>Hi <%=@user.name%>, here is your profile</h3>

<p>
  <strong>Email:</strong>
  <%= @user.email%>
</p>
<br>
<p>
  <strong>Reality User Type:</strong>
  <%= @user.user_type%>
</p>
<br>